sudo: required
services:
  - docker

before_install:
  - docker build -t fadihafez/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true fadihafez/react-test npm test

after_success:
  - docker build -t fadihafez/multi-client ./client
  - docker build -t fadihafez/multi-nginx ./nginx
  - docker build -t fadihafez/multi-server ./server
  - docker build -t fadihafez/multi-worker ./worker

  # login to docker CLI and push the images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push fadihafez/multi-client
  - docker push fadihafez/multi-nginx
  - docker push fadihafez/multi-server
  - docker push fadihafez/multi-worker
